# to run prod enviornment, run:
# jekyll build
# you shouldn't need to do this; github actions should handle this
# unless you have a baseurl like i do (i hate it here)

title: rovi_blog
email: johnrcd.ar@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  blog about code, music, and games
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://rovidecena.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: john_rcd
github_username:  john_rcd

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme_config:
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%-d %B %Y" # customize how date is formatted

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      description: "[no description provided]"

# jekyll-toc settings
toc:
  min_level: 1
  max_level: 5
  list_class: toc
  list_class: toc__list
  sublist_class: toc__sublist

kramdown:
  footnote_backlink: ""
  footnote_backlink_inline: true

collections:
  posts:
    output: true
    permalink: /posts/:title/
  drafts:
    output: true
    permalink: /drafts/:title/


