# to run dev enviornment, run:
# jekyll serve --config _config.yml,_config_dev.yml

# to include post drafts, run:
# jekyll serve --config _config.yml,_config_dev.yml --draft

environment: development
baseurl: ""
url: ""